#+TODO: NEXT INPROC   | DONE REMEMBER RESOLVED REWRITE WAITINGON REASSIGNED COULDNT-DO
#+TAGS: { @s_active @s_next @s_planning @s_postponed @s_someday @s_waiting_on } 
#+TAGS: { @c_bus @c_coffee_shop @c_home @c_phone @c_shopping @c_work } 
#+TAGS: { @r_invoices @r_meetingnotes @r_receipts }
#+TAGS: { @p_fll @p_ds @p_nj }

* REFERENCE

  http://rvm.beginrescueend.com/
  http://progit.org/book/ch1-4.html



* BASIC

** SETUP
   
   $ rvm install ruby-1.9.2-p136
   $ rvm --create use 1.9.2@rails3tutorial
   $ rvm --default use 1.9.2@rails3tutorial
   $ gem install rails --version 3.0.3
   $ git config --global alias.co checkout
   $ git config --global core.editor "/Applications/Emacs.app/Contents/MacOS/bin/emacsclient

** DEVELOP

   $ rails new my_app
   <edit .gitignore>
   $ git init

   <edit Gemfile>
   $ bundle install

   $ rails server
   <C-c C-c>

   $ git add .
   $ git commit -m "Initial commit"
   $ git checkout -b modify-README # 3 commands always done together except 1st time

   <edits>

   <$ git checkout -f # restores if not added or commited>

   <create new repo on github https://github.com/repositories/new & link to existing>
   < $ git remote add origin git@github.com:ChasManRors/usfirst_app.git> # only 1st time.
   $ git push origin master

   < $ git mv README README.markdown> # to rename files

   $ git commit -am "Improve the README file" # to commit changed files




** TEARDOWN

   $ rvm system


* Get computer up to speed on Rails 3

*** bash-3.2$ gem list LOCAL GEMS pre RVM ***

    actionmailer (2.3.5, 2.3.2, 1.3.6)
    actionpack (2.3.5, 2.3.2, 1.13.6)
    actionwebservice (1.2.6)
    activerecord (2.3.5, 2.3.2, 1.15.6)
    activeresource (2.3.5, 2.3.2)
    activesupport (3.0.0, 2.3.5, 2.3.2, 1.4.4)
    acts_as_ferret (0.4.3)
    authlogic (2.1.6)
    aws-s3 (0.6.2)
    builder (2.1.2)
    calendar_date_select (1.16.1)
    capistrano (2.5.19, 2.5.2)
    capistrano-ext (1.2.1)
    cgi_multipart_eof_fix (2.5.0)
    cheat (1.3.0)
    colored (1.2)
    columnize (0.3.1)
    daemons (1.0.10)
    dnssd (0.6.0)
    fast_xor (1.0.1)
    fastthread (1.0.1)
    fcgi (0.8.7)
    ferret (0.11.6)
    gcal4ruby (0.5.5)
    gdata4ruby (0.1.5)
    gem_plugin (0.2.3)
    gemcutter (0.6.1)
    geokit (1.3.0)
    git (1.2.5)
    git_remote_branch (0.3.0)
    highline (1.5.0)
    hpricot (0.6.164)
    jeweler (1.4.0)
    json_pure (1.4.6)
    libxml-ruby (1.1.2)
    linecache (0.43)
    mime-types (1.16)
    mongrel (1.1.5)
    mysql (2.8.1)
    needle (1.3.0)
    net-scp (1.0.1)
    net-sftp (2.0.1, 1.1.1)
    net-ssh (2.0.23, 2.0.4, 1.1.4)
    net-ssh-gateway (1.0.0)
    prawn (0.4.1)
    prawn-layout (0.8.4)
    rack (1.0.1)
    rails (2.3.5, 2.3.2, 1.2.6)
    rake (0.8.3)
    RedCloth (4.1.1)
    right_aws (2.0.0)
    right_http_connection (1.2.4)
    ruby-debug (0.10.3)
    ruby-debug-base (0.10.3)
    ruby-debug-ide (0.4.9)
    ruby-openid (2.1.2)
    ruby-yadis (0.3.4)
    rubyforge (2.0.4)
    rubygems-update (1.3.7)
    rubynode (0.1.5)
    rubyzip (0.9.4)
    searchlogic (2.4.26)
    sqlite3-ruby (1.2.4)
    termios (0.9.4)
    vpim (0.695)
    xml-simple (1.0.12)
    xmpp4r (0.4)

*** Ruby Version Manager (RVM) Quick Install

**** REMEMBER URL http://rvm.beginrescueend.com/

*** Commands for installation of RVM

**** REMEMBER $ bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )

*** Output from install RVM command

    bash-3.2$ bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
    109   986  109   986    0     0   4768      0 --:--:-- --:--:-- --:--:--  9572
    Cloning into rvm...
    remote: Counting objects: 16788, done.        
    remote: Compressing objects: 100% (4688/4688), done.        
    remote: Total 16788 (delta 11314), reused 15837 (delta 10649)        
    Receiving objects: 100% (16788/16788), 2.96 MiB | 2.52 MiB/s, done.
    Resolving deltas: 100% (11314/11314), done.

    RVM:  Shell scripts enabling management of multiple ruby environments.
    RTFM: http://rvm.beginrescueend.com/
    HELP: http://webchat.freenode.net/?channels=rvm (#rvm on irc.freenode.net)

    Installing RVM to /Users/cmmagid/.rvm/
    Correct permissions for base binaries in /Users/cmmagid/.rvm/bin...
    Copying manpages into place.

    Notes for Darwin ( Mac OS X )
    [DONE]    For Snow Leopard be sure to have Xcode Tools Version 3.2.1 (1613) or later
    You should download the latest Xcode tools from developer.apple.com.
    (This is since the dvd install for Snow Leopard contained bugs).

    [NO]    If you intend on installing MacRuby you must install LLVM first.
    [NO]    If you intend on installing JRuby you must install the JDK.
    [NO]    If you intend on installing IronRuby you must install Mono (version 2.6 or greater is recommended).

    To seamlessly abandon the Apple-installed system ruby (ruby 1.8.7 patchlevel 174 for Snow Leopard):

    rvm install 1.8.7 # installs patch 302: closest supported version
    rvm system ; rvm gemset export system.gems ; rvm 1.8.7 ; rvm gemset import system # migrate your gems
    rvm --default 1.8.7
    

    You must now complete the install by loading RVM in new shells.

  1) Place the folowing line at the end of your shell's loading files
     (.bashrc or .bash_profile for bash and .zshrc for zsh),
     after all PATH/variable settings:

     [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

     You only need to add this line the first time you install rvm.

  2) Ensure that there is no 'return' from inside the ~/.bashrc file,
     otherwise rvm may be prevented from working properly.

     
    This means that if you see something like:

    '[ -z "$PS1" ] && return'

    then you change this line to:

    if [[ -n "$PS1" ]] ; then

    # ... original content that was below the '&& return' line ...

    fi # <= be sure to close the if at the end of the .bashrc.

    # This is a good place to source rvm v v v
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

    EOF - This marks the end of the .bashrc file

    Be absolutely *sure* to REMOVE the '&& return'.

    If you wish to DRY up your config you can 'source ~/.bashrc' at the bottom of your .bash_profile.

    Placing all non-interactive (non login) items in the .bashrc,
    including the 'source' line above and any environment settings.

  3) CLOSE THIS SHELL and open a new one in order to use rvm.
     

    Installation of RVM to /Users/cmmagid/.rvm/ is complete.


    Charles Magid,

    Thank you very much for using RVM! I sincerely hope that RVM helps to
    make your work both easier and more enjoyable.

    If you have any questions, issues and/or ideas for improvement please
    join#rvm on irc.freenode.net and let me know, note you must register
    (http://bit.ly/5mGjlm) and identify (/msg nickserv <nick> <pass>) to
    talk, this prevents spambots from ruining our day.

    My irc nickname is 'wayneeseguin' and I hang out in #rvm typically

    ~09:00-17:00EDT and again from ~21:00EDT-~23:00EDT

    If I do not respond right away, please hang around after asking your
    question, I will respond as soon as I am back.  It is best to talk in
    #rvm itself as then other users can help out should I be offline.

    Be sure to get head often as rvm development happens fast,
    you can do this by running 'rvm get head' followed by 'rvm reload'
    or opening a new shell

    w⦿‿⦿t

    ~ Wayne

*** Command for install of rubys
    rvm install ree,1.9.2-head,jruby
*** Output for install of rubys

    bash-3.2$ rvm install ree,1.9.2-head,jruby
    /Users/cmmagid/.rvm/rubies/ree-1.8.7-2010.02
    ree-1.8.7-2010.02 - #fetching (ruby-enterprise-1.8.7-2010.02)
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
    100 7629k  100 7629k    0     0  1979k      0  0:00:03  0:00:03 --:--:-- 2032k
    ree-1.8.7-2010.02 - #extracting ruby-enterprise-1.8.7-2010.02 to /Users/cmmagid/.rvm/src/ree-1.8.7-2010.02
    ree-1.8.7-2010.02 - #installing 
    ree-1.8.7-2010.02 - #rubygems installing to ree-1.8.7-2010.02
    ree-1.8.7-2010.02 - adjusting #shebangs for (gem).
    ree-1.8.7-2010.02 - #importing default gemsets (/Users/cmmagid/.rvm/gemsets/)
    /Users/cmmagid/.rvm/rubies/ruby-1.9.2-head, this may take a while depending on your cpu(s)...

    ruby-1.9.2-head - #fetching 
    Cloning from https://github.com/ruby/ruby.git, this may take a while depending on your connection...
    Cloning into /Users/cmmagid/.rvm/repos/ruby-1.9.2-head...
    remote: Counting objects: 30912, done.        
    remote: Compressing objects: 100% (14068/14068), done.        
    remote: Total 30912 (delta 23368), reused 22651 (delta 16104)        
    Receiving objects: 100% (30912/30912), 21.44 MiB | 1.07 MiB/s, done.
    Resolving deltas: 100% (23368/23368), done.
    Branch ruby_1_9_2 set up to track remote branch ruby_1_9_2 from origin.
    Switched to a new branch 'ruby_1_9_2'
    From https://github.com/ruby/ruby
 * branch            ruby_1_9_2 -> FETCH_HEAD
    Already up-to-date.
    Copying from repo to src path...
    Running autoconf
    ruby-1.9.2-head - #configuring 
    ruby-1.9.2-head - #compiling 
    ruby-1.9.2-head - #installing 
    ruby-1.9.2-head - updating #rubygems for /Users/cmmagid/.rvm/gems/ruby-1.9.2-head@global
    ruby-1.9.2-head - updating #rubygems for /Users/cmmagid/.rvm/gems/ruby-1.9.2-head
    ruby-1.9.2-head - adjusting #shebangs for (gem).
    ruby-1.9.2-head - #importing default gemsets (/Users/cmmagid/.rvm/gemsets/)
    Install of ruby-1.9.2-head - #complete 
    jruby-1.5.6 - #fetching 
    jruby-1.5.6 - #downloading jruby-bin-1.5.6, this may take a while depending on your connection...
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
   Dload  Upload   Total   Spent    Left  Speed
    100 10.9M  100 10.9M    0     0  1160k      0  0:00:09  0:00:09 --:--:-- 1408k
    jruby-1.5.6 - #extracting jruby-bin-1.5.6 to /Users/cmmagid/.rvm/src/jruby-1.5.6
    jruby-1.5.6 - #extracted to /Users/cmmagid/.rvm/src/jruby-1.5.6
    Building Nailgun
    jruby-1.5.6 - #installing to /Users/cmmagid/.rvm/rubies/jruby-1.5.6
    jruby-1.5.6 - #importing default gemsets (/Users/cmmagid/.rvm/gemsets/)
    Copying across included gems
    Building native extensions.  This could take a while...
    Successfully installed jruby-launcher-1.0.5-java
    1 gem installed

*** REMEMBER Command to create sets of gems ie gemsets
**** Modified 1.8.7
# $ rvm --create 1.8.7-p174@rails2tutorial
     $ rvm --create 1.8.7@rails2tutorial
**** Ran this command and the system told me to modify the command I am issuing
     $ rvm --create use 1.9.2@rails3tutorial
**** Here is its output
     warn: ruby ruby-1.9.2-p136 is not installed.
     To install do: 'rvm install ruby-1.9.2-p136'
*** So I ran the following to get ruby 1.9.2 patch 136
    $ rvm install ruby-1.9.2-p136
*** I got this output, after waiting a long time
    $ rvm install ruby-1.9.2-p136
    /Users/cmmagid/.rvm/rubies/ruby-1.9.2-p136, this may take a while depending on your cpu(s)...

    ruby-1.9.2-p136 - #fetching 
    ruby-1.9.2-p136 - #downloading ruby-1.9.2-p136, this may take a while depending on your connection...
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
    100 8612k  100 8612k    0     0   663k      0  0:00:12  0:00:12 --:--:-- 1474k
    ruby-1.9.2-p136 - #extracting ruby-1.9.2-p136 to /Users/cmmagid/.rvm/src/ruby-1.9.2-p136
    ruby-1.9.2-p136 - #extracted to /Users/cmmagid/.rvm/src/ruby-1.9.2-p136
    ruby-1.9.2-p136 - #configuring 
    ruby-1.9.2-p136 - #compiling 
    ruby-1.9.2-p136 - #installing 
    ruby-1.9.2-p136 - updating #rubygems for /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@global
    ruby-1.9.2-p136 - updating #rubygems for /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136
    ruby-1.9.2-p136 - adjusting #shebangs for (gem).
    ruby-1.9.2-p136 - #importing default gemsets (/Users/cmmagid/.rvm/gemsets/)
    Install of ruby-1.9.2-p136 - #complete 
    bash-3.2$ 
*** create another gem set

    rvm --create use 1.9.2-p136@rails3tutorial

*** Tell system to use this by default

    rvm --default use 1.9.2-p136@rails3tutorial

*** Run command to update gems in above gemset

    $ gem update --system

*** UNSUCCESSFUL run, output is

    Updating RubyGems
    Updating rubygems-update
    Successfully installed rubygems-update-1.4.2
    Updating RubyGems to 1.4.2
    Installing RubyGems 1.4.2
    /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems/source_index.rb:62:in `installed_spec_directories': undefined method `path' for Gem:Module (NoMethodError)
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems/source_index.rb:52:in `from_installed_gems'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems.rb:914:in `source_index'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems/gem_path_searcher.rb:83:in `init_gemspecs'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems/gem_path_searcher.rb:13:in `initialize'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems.rb:873:in `new'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems.rb:873:in `searcher'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems.rb:495:in `find_files'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems.rb:1034:in `load_plugins'
    from /Users/cmmagid/.rvm/gems/ruby-1.9.2-p136@rails3tutorial/gems/rubygems-update-1.4.2/lib/rubygems/gem_runner.rb:84:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from setup.rb:25:in `<main>'

*** Make sure I am using the default set

    $ rvm 1.9.2-p136@rails3tutorial

*** Now install Rails 3.0.3

    $ gem install rails --version 3.0.3

*** output
    Successfully installed activesupport-3.0.3
    Successfully installed builder-2.1.2
    Successfully installed i18n-0.5.0
    Successfully installed activemodel-3.0.3
    Successfully installed rack-1.2.1
    Successfully installed rack-test-0.5.7
    Successfully installed rack-mount-0.6.13
    Successfully installed tzinfo-0.3.23
    Successfully installed abstract-1.0.0
    Successfully installed erubis-2.6.6
    Successfully installed actionpack-3.0.3
    Successfully installed arel-2.0.6
    Successfully installed activerecord-3.0.3
    Successfully installed activeresource-3.0.3
    Successfully installed mime-types-1.16
    Successfully installed polyglot-0.3.1
    Successfully installed treetop-1.4.9
    Successfully installed mail-2.2.14
    Successfully installed actionmailer-3.0.3
    Successfully installed thor-0.14.6
    Successfully installed railties-3.0.3
    Successfully installed bundler-1.0.7
    Successfully installed rails-3.0.3
    23 gems installed

*** Return from working on bugs in usfirst Fri Jan 14 15:10:51 2011

    rvm --default use 1.9.2-p136@rails3tutorial

* REMEMBER VERY IMPORTANT

  To revert back to the initial state of the system use the following:

  $ rvm system

* REMEMBER for rails tutorial 

  $ rvm --default use 1.9.2@rails3tutorial

* install all gems

** REMEMBER $ bundle install

   rvm ruby-1.9.2-p136@rails3tutorial

